# Generated by Django 3.1.1 on 2020-10-23 08:16

from django.db import migrations, models
import django.db.models.deletion
import hotel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=10)),
                ('booking_no', models.CharField(default=hotel.models.booking_no_generator, max_length=20)),
                ('id_type', models.CharField(choices=[('Aadhaar Card', 'Aadhaar Card'), ('PAN Card', 'PAN Card'), ('Voter ID', 'Voter ID'), ('Passport', 'Passport'), ('Driving License', 'Driving License')], default='Aadhaar Card', max_length=25)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('address', models.TextField()),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(null=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('query_msg', models.TextField()),
                ('query_response', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('image', models.ImageField(default='fac.jpg', upload_to='fac_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=100)),
                ('maxadult', models.IntegerField()),
                ('maxchild', models.IntegerField()),
                ('roomdesc', models.TextField()),
                ('no_of_bed', models.IntegerField()),
                ('image', models.ImageField(default='room.jpg', upload_to='room_pics')),
                ('roomfacility', models.TextField()),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.category')),
            ],
        ),
    ]
