# Generated by Django 3.1.1 on 2020-10-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20201023_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomfacility',
        ),
        migrations.AddField(
            model_name='room',
            name='roomfacility',
            field=models.ManyToManyField(to='hotel.Facilities'),
        ),
    ]
