# Generated by Django 3.1.1 on 2020-10-24 19:08

from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20201024_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateField(validators=[hotel.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateField(validators=[hotel.models.validate_date]),
        ),
    ]
